### ISSUE TITLE
No site updating

### ISSUE THREAD

**Issue by CRprog** [pangodream/ESP2SOTA#1]
Nice little help that also works regarding the OTA update.
I tested client mode (-> browser) and AP mode (-> mobile phone).
But unfortunately the progress bar is not updated (on mobile and browsers like Firefox/Edge) and stays at 0%.
I usually see the final OK/failed output on my cell phone, but never in the browser display.
Maybe something is missing in the HTML script area?
Regards.

P.S.: 
I've revised the index_html.h a bit so that the HTML can be edited more easily.
The HTML code itself is expanded for full screen display without zooming every time.
Use it as you like.
[index_html.zip](https://github.com/pangodream/ESP2SOTA/files/10149411/index_html.zip)

**Comment by pangodream** [comment]
Thanksa lot for your contribution. Unfortunately I have no time to make enhancements to the library. Best reagrds.
