### ISSUE TITLE
Custom index_html.h?

### ISSUE THREAD

**Issue by Xylopyrographer** [pangodream/ESP2SOTA#2]
Certainly appreciate the effort you put into making this library. Many thanks.

Would it be possible to modify the library so that a custom `index_html.h` file could be passed rather than using the one coded into the library?

Or have an `index_html.h` file in the same project directory as the `.ino` file override the one in the library?

I did take a look at the source but my C++ skills aren't there yet to propose a PR.

**Comment by pangodream** [comment]
Thanks for your suggestion. Unfortunately I have no time to make enhancements to the library. Best reagrds.
