### ISSUE TITLE
Esp32 wifi disconnects while bin file transfer

### ISSUE THREAD

**Issue by malpaniankit** [pangodream/ESP2SOTA#5]
I am running ESP2SOTA on ESP32 as AP, somehow, wifi keeps getting disconnected during update file transfer, and hence the progress bar stops.  I would have to try 10 or more time to success once. 

shorter files of program code goes through without issues, may be , the transfer completes before disconnection.

any help would be appreciated.

**Comment by pangodream** [comment]
The library has nothing to do with that issue. It relays on HttpWebserver to establish the connection and keep it alive.
